### ISSUE TITLE
Invalid current library on PASE gives an empty error message

### ISSUE THREAD

**Issue by NattyNarwhal** [php/pecl-database-pdo_ibm#7]
In a test case I'm writing, based on a client issue:

```
Fatal error: Uncaught PDOException: SQLSTATE[]: <<Unknown error>>:  (SQLSetConnectAttr[0] at /home/calvin/src/pecl-database-pdo_ibm/ibm_driver.c:651) in /home/calvin/src/pecl-database-pdo_ibm/tests/fvt_curlib_after.php:11
Stack trace:
#0 /home/calvin/src/pecl-database-pdo_ibm/tests/fvt_curlib_after.php(11): PDO->setAttribute(1013, 'DB22') // <- this is the current lib set here
#1 /home/calvin/src/pecl-database-pdo_ibm/tests/fvt_curlib_after.php(18): Test->runTest()
#2 {main}
  thrown in /home/calvin/src/pecl-database-pdo_ibm/tests/fvt_curlib_after.php on line 11
```

If you change the logic around, it does seem the database is getting the info:

```
(gdb) cont
Continuing.
rc: 0
rc: -1

Breakpoint 2, raise_sql_error (dbh=0x70000000008e0c0, stmt=0x0, handle=3, hType=3, tag=0xffffffffffecb18 "", file=0x900000000bab4a0 <_iconvTable_Lower_exec> "|\b\002\246\370!\377\021\370\001\001", line=54)
    at /home/calvin/src/pecl-database-pdo_ibm/ibm_driver.c:1340
warning: Source file is more recent than executable.
1340            if(hType == SQL_HANDLE_STMT) {
(gdb) p conn_res->error_data
$1 = {sqlcode = -443, filename = 0x9000000615f7db0 <stmt_bind_parameter+204> "/home/calvin/src/pecl-database-pdo_ibm/ibm_driver.c", lineno = 1450, failure_name = 0x9000000615f7de8 <stmt_bind_parameter+260> "db2_ibmi_cmd_helper", 
  sql_state = "38501\000\000", err_msg = "Trigger program or external routine detected an error.", '\000' <repeats 458 times>, isam_err_msg = '\000' <repeats 518 times>}
```

In the current implementation, my guess is the SQLFreeHandle eats the error, and the error handling should thus be moved from the caller to the callee. However, I had some issues with it not throwing any error when I implemented it like that unless I forced it to use the manually throwing error case (which is only used in early PDO init).

**Comment by praveen-db2** [comment]
@NattyNarwhal is this fixed, can we close it.

**Comment by NattyNarwhal** [comment]
No, still need to diagnose.

**Comment by NattyNarwhal** [comment]
I believe this is because the [callsite](https://github.com/php/pecl-database-pdo_ibm/blob/RELEASE_1_5_0/ibm_driver.c#L651) is checking the database connection handle for errors, when the error here is occurring in the [statement that actually sets the current library](https://github.com/php/pecl-database-pdo_ibm/blob/RELEASE_1_5_0/ibm_driver.c#L1448). We're getting `SQL_NO_DATA` when we `SQLGetDiagRec` the connection handle. This will need a mild refactor.
